"""empty message

Revision ID: 6e2fc155effd
Revises: 
Create Date: 2021-08-02 22:38:08.561363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2fc155effd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_birth', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('pairing_code',
    sa.Column('pair_code', sa.String(), nullable=False),
    sa.Column('pair_expiry', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pair_code')
    )
    op.create_table('pantry_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_label', sa.String(), nullable=False),
    sa.Column('item_image', sa.LargeBinary(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_pantry_item_item_label'), 'pantry_item', ['item_label'], unique=False)
    op.create_index(op.f('ix_pantry_item_item_quantity'), 'pantry_item', ['item_quantity'], unique=False)
    op.create_table('robot_preset',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('preset_label', sa.String(), nullable=True),
    sa.Column('preset_x', sa.Integer(), nullable=False),
    sa.Column('preset_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('preset_id')
    )
    op.create_table('pantry_audit',
    sa.Column('reciept_id', sa.Integer(), nullable=False),
    sa.Column('reciept_time', sa.DateTime(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('label_old', sa.String(), nullable=True),
    sa.Column('label_new', sa.String(), nullable=True),
    sa.Column('image_old', sa.LargeBinary(), nullable=True),
    sa.Column('image_new', sa.LargeBinary(), nullable=True),
    sa.Column('quant_old', sa.Integer(), nullable=True),
    sa.Column('quant_new', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['pantry_item.item_id'], ),
    sa.PrimaryKeyConstraint('reciept_id')
    )
    op.create_index(op.f('ix_pantry_audit_reciept_time'), 'pantry_audit', ['reciept_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pantry_audit_reciept_time'), table_name='pantry_audit')
    op.drop_table('pantry_audit')
    op.drop_table('robot_preset')
    op.drop_index(op.f('ix_pantry_item_item_quantity'), table_name='pantry_item')
    op.drop_index(op.f('ix_pantry_item_item_label'), table_name='pantry_item')
    op.drop_table('pantry_item')
    op.drop_table('pairing_code')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
