"""empty message

Revision ID: a464538db648
Revises: 
Create Date: 2021-09-23 13:44:52.736824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a464538db648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('token_data', sa.String(), nullable=False),
    sa.Column('token_class', sa.String(), nullable=False),
    sa.Column('token_birth', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_data')
    )
    op.create_table('pairing_code',
    sa.Column('pair_code', sa.String(), nullable=False),
    sa.Column('pair_expiry', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pair_code')
    )
    op.create_table('pantry_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_label', sa.String(), nullable=False),
    sa.Column('item_image', sa.LargeBinary(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('item_x', sa.Integer(), nullable=False),
    sa.Column('item_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_pantry_item_item_label'), 'pantry_item', ['item_label'], unique=False)
    op.create_index(op.f('ix_pantry_item_item_quantity'), 'pantry_item', ['item_quantity'], unique=False)
    op.create_table('robot_preset',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('preset_label', sa.String(), nullable=True),
    sa.Column('preset_x', sa.Integer(), nullable=False),
    sa.Column('preset_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('preset_id')
    )
    op.create_table('system_status',
    sa.Column('status_time', sa.DateTime(), nullable=False),
    sa.Column('status_state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('status_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_status')
    op.drop_table('robot_preset')
    op.drop_index(op.f('ix_pantry_item_item_quantity'), table_name='pantry_item')
    op.drop_index(op.f('ix_pantry_item_item_label'), table_name='pantry_item')
    op.drop_table('pantry_item')
    op.drop_table('pairing_code')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
