"""empty message

Revision ID: 868a1542b1c3
Revises: 8db7178362d0
Create Date: 2021-10-13 23:37:34.771220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868a1542b1c3'
down_revision = '8db7178362d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantryitem',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_label', sa.String(), nullable=False),
    sa.Column('item_image', sa.LargeBinary(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('item_x', sa.Integer(), nullable=False),
    sa.Column('item_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_pantryitem_item_label'), 'pantryitem', ['item_label'], unique=False)
    op.create_index(op.f('ix_pantryitem_item_quantity'), 'pantryitem', ['item_quantity'], unique=False)
    op.create_table('robotpreset',
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('preset_label', sa.String(), nullable=True),
    sa.Column('preset_x', sa.Integer(), nullable=False),
    sa.Column('preset_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('preset_id'),
    sqlite_autoincrement=True
    )
    op.drop_index('ix_pantry_item_item_label', table_name='pantry_item')
    op.drop_index('ix_pantry_item_item_quantity', table_name='pantry_item')
    op.drop_table('pantry_item')
    op.drop_table('robot_preset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_preset',
    sa.Column('preset_id', sa.INTEGER(), nullable=False),
    sa.Column('preset_label', sa.VARCHAR(), nullable=True),
    sa.Column('preset_x', sa.INTEGER(), nullable=False),
    sa.Column('preset_y', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('preset_id')
    )
    op.create_table('pantry_item',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('item_label', sa.VARCHAR(), nullable=False),
    sa.Column('item_image', sa.BLOB(), nullable=True),
    sa.Column('item_quantity', sa.INTEGER(), nullable=False),
    sa.Column('item_x', sa.INTEGER(), nullable=False),
    sa.Column('item_y', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('ix_pantry_item_item_quantity', 'pantry_item', ['item_quantity'], unique=False)
    op.create_index('ix_pantry_item_item_label', 'pantry_item', ['item_label'], unique=False)
    op.drop_table('robotpreset')
    op.drop_index(op.f('ix_pantryitem_item_quantity'), table_name='pantryitem')
    op.drop_index(op.f('ix_pantryitem_item_label'), table_name='pantryitem')
    op.drop_table('pantryitem')
    # ### end Alembic commands ###
